# Generated by Django 5.2.5 on 2025-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('era', models.CharField(max_length=100)),
                ('site_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
